admin-manual/provisioning_gateway.rst
admin-manual/provisioning_phone.rst

Provisioning fix syntax with semantic markup

Provisioning fix syntax with semantic markup

---

admin-manual/wizard.rst

add param urls wizard section

---

admin-manual/wizard.rst

https://github.com/nethesis/dev/issues/5401

Update CSV Import/Export

---

admin-manual/directdid.rst
admin-manual/howto.rst
admin-manual/inbound_report.rst
admin-manual/index.rst
admin-manual/nethcqr.rst
admin-manual/queue_report.rst
admin-manual/queueexit.rst
admin-manual/queuemetrics.rst
admin-manual/rapid_code.rst
admin-manual/returnonblindtransfer.rst

Add:
- directdid
- queueexit
- queuemetrics
- return on blind 
- how to phonebook
- how to iax trunks

Add new modules documentation

---

admin-manual/index.rst
admin-manual/migrazione.rst

https://github.com/nethesis/dev/issues/5454

Migration from NethVoice11 to NethVoice14

---

admin-manual/app_mobile.rst
admin-manual/dashboard.rst
admin-manual/index.rst
admin-manual/migrazione.rst
admin-manual/queue_report.rst
admin-manual/wizard.rst

Add docs for:
- Fix ivr choice page in Queue Report nethesis/dev#5550
- Migration nethesis/dev#5454
- Dashboard nethesis/dev#5544
- Wave app nethesis/dev#5531
- syntax fixes

Docs for new update

---

admin-manual/migrazione.rst
admin-manual/queue_report.rst
admin-manual/release_notes.rst

Add migration on release notes

Add migration on release notes

---

admin-manual/howto.rst
admin-manual/inbound_report.rst
admin-manual/nethcqr.rst
admin-manual/queue_report.rst
admin-manual/queuemetrics.rst
admin-manual/returnonblindtransfer.rst
admin-manual/wizard.rst

fix accented E thanks to @Stell0 keyboard

fix accented E

---

admin-manual/app_mobile.rst
admin-manual/howto.rst
admin-manual/provisioning_phone.rst

Remove Alcatel support

---

admin-manual/app_mobile.rst

Typo fixes for app mobile section.

Typo fixes for app mobile section

---

admin-manual/howto.rst

Cti: how to customize login warning message on not configured user

---

admin-manual/wizard.rst

New section: phonebook impoter

---

admin-manual/howto.rst

NethCTI: added doc to execute custom script on cdr event

---

admin-manual/howto.rst

Add cti dashboard section

---

admin-manual/locale/en/LC_MESSAGES/howto.po

add i18n dashboard alarms cti

---

admin-manual/migrazione.rst

Add configuration that the migration tool doesn't move to the new version

Add migration exclude

---

admin-manual/app_mobile.rst

IOS new version (1.2.11) add provisioning function

Add ios provisioning

---

admin-manual/provisioning_phone.rst

Comment PNP

---

admin-manual/index.rst
admin-manual/locale/en/LC_MESSAGES/app_mobile.po
admin-manual/locale/en/LC_MESSAGES/howto.po
admin-manual/locale/en/LC_MESSAGES/index.po
admin-manual/locale/en/LC_MESSAGES/provisioning_phone.po
admin-manual/locale/es/LC_MESSAGES/app_mobile.po
admin-manual/locale/es/LC_MESSAGES/index.po
admin-manual/queueoptions.rst

https://github.com/nethesis/dev/issues/5642

 Add Queue Options module 

---

admin-manual/cti_dev.rst

Cti doc to use tancredi/corbera rest api

---

admin-manual/_static/nethesis.css
admin-manual/provisioning_phone.rst
admin-manual/provisioning_phone2.rst
admin-manual/release_notes.rst
admin-manual/wizard.rst
admin-manual/wizard2.rst

- New provisioning_phone2 page
- Release notes
- New wizard2 page

Leopard provisioning

---

admin-manual/app_mobile.rst

Change SSL Method to Default

---

admin-manual/app_mobile.rst

Add requires for NethCTI App

---

admin-manual/wizard2.rst

Explain configuration priority and configuration page

---

admin-manual/release_notes.rst

Update release note

---

admin-manual/wizard.rst
admin-manual/wizard2.rst

- Add new configurations on Settings page
- Add new configurations on models default setting

Add new configuration parameters on settings page and models default config

---

admin-manual/app_mobile.rst

Add alias domain configuration for app push notification.

Add alias domain configuration

---

admin-manual/app_mobile.rst

Fix command output

---

admin-manual/howto.rst

cti: execute script for each external incoming call

---

admin-manual/provisioning_phone2.rst

https://github.com/nethesis/dev/issues/5800

Add new provisioning Firmware upgrade

---

admin-manual/conf.py
admin-manual/index.rst
admin-manual/provisioning_phone2.rst
admin-manual/wizard2.rst
admin-manual/wizard2_provisioning.rst

https://github.com/nethesis/dev/issues/5833

Add details of Model panels

---

admin-manual/provisioning_migration.rst
admin-manual/provisioning_phone2.rst
admin-manual/wizard2.rst

Import the migration procedure

---

admin-manual/index.rst
admin-manual/provisioning_phone.rst
admin-manual/provisioning_phone2.rst
admin-manual/wizard.rst
admin-manual/wizard2.rst
admin-manual/wizard2_others.rst

- Restore all wizard sections
- Split Applications on other section
- Link obsolete provisioning manual in obsolete wizard manual
- Better specified model and firmware required

Restore all wizard sections on main manual

---

admin-manual/index.rst
admin-manual/provisioning_phone.rst
admin-manual/provisioning_phone2.rst
admin-manual/wizard.rst
admin-manual/wizard2.rst
admin-manual/wizard2_others.rst

* Split Application on other section
* Link obsolete provioning manual in obsolete wizard manual
* Better specified model and firmware required
* Restore all wizard sections
* Change guilabel with ref for new section Application
* Syntax fixes

Update v14 branch

---

admin-manual/wizard2_provisioning.rst

Minor improvements

---

admin-manual/release_notes.rst
admin-manual/wizard2.rst

Leopard release notes

---

admin-manual/provisioning_phone2.rst

Add Fanvil X1

---

admin-manual/wizard2.rst

- advanced interface specification

Advanced interface specification

---

admin-manual/howto.rst

The procedure is now based on a new RPM: asterisk-codecs-g729
https://github.com/nethesis/dev/issues/5896

Fix g729 codec section

---

admin-manual/app_mobile.rst

Provisioning of wave app is no longer possible with Tancredi provisioning engine

Provisioning of Wave app only with old system

---

admin-manual/index.rst
admin-manual/report.rst

Nethesis/dev#5865
See also nethesis/comps#49

Add nethvoice-report

---

admin-manual/_static/nethesis.css
admin-manual/wizard2_others.rst

https://github.com/nethesis/dev/issues/5903

Phonebook CSV source type docs

---

admin-manual/wizard2_others.rst

Add phonebook fields

---

admin-manual/app_mobile.rst

Add a note for using app only with old provisioning

Scan & Play only old provisioning

---

admin-manual/hotel.rst

https://github.com/nethesis/dev/issues/5901

Add FIAS documentation

---

admin-manual/app_mobile.rst
admin-manual/index.rst
admin-manual/report.rst
admin-manual/wizard2_others.rst

- Add phonebook source fields and descriptions
- Add FIAS https://github.com/nethesis/dev/issues/5901

Merge in v14 last changes from master branch

---

admin-manual/report.rst

Expand NethVoice report documentation
nethesis/dev#5907

updated report queue and cost docs

---

admin-manual/index.rst

Link: added the link of the old version of nethvoice

Added the link of the old version of nethvoice

---

admin-manual/app_mobile.rst

Add proxy port to app specs

---

admin-manual/app_mobile.rst

Simplification of ALIAS configuration

Simplification of ALIAS configuration

---

admin-manual/provisioning_phone2.rst

Add Fanvil X7C in supported list

Add Fanvil X7C in supported list

---

admin-manual/app_mobile.rst

TLS is now configured on every NethVoice

Remove TLS configuration from App

---

admin-manual/hotel.rst

Add FIAS compatible version
Add PMS compatible version

Add FIAS specs.

---

admin-manual/howto.rst

Add CTI video conf configuration section

---

admin-manual/index.rst
admin-manual/queue_report.rst
admin-manual/report.rst

NethVoice Report is official, move from beta.

NethVoice Report is official

---

admin-manual/hotel.rst

Syntax fix

---

.travis.yml
admin-manual/_static/nethesis.css

Nethvoice-docs: cosmetic fix

---

admin-manual/report.rst

Change rate per minute

---

admin-manual/_static/nethesis.css
admin-manual/index.rst
admin-manual/report.rst

Publish latest fix inside the stable branch

Pull latest changes

---

admin-manual/wizard2.rst

Add Video Conference

---

admin-manual/provisioning_phone2.rst

Add Nethphone, new Nethesis phone (X3, X5)

Add Nethphone

---

admin-manual/hotel.rst
admin-manual/wizard.rst
admin-manual/wizard2.rst
admin-manual/wizard2_others.rst

New NethVoice update [here](https://partner.nethesis.it/t/nuovo-pacchetto-aggiornamenti-nethvoice-da-provare/5430)

Fix docs for new Nethvoice update

---

admin-manual/hotel.rst

Reported the section "Add outbound dialtone" from v11 and adapted it for v14

NethHotel added section Add outbound dialtone

---

admin-manual/_static/nethesis.css
admin-manual/cti_dev.rst
admin-manual/hotel.rst
admin-manual/howto.rst
admin-manual/wizard.rst
admin-manual/wizard2.rst
admin-manual/wizard2_others.rst

- Fix docs css
- Update doc for context-profiles https://github.com/nethesis/dev/issues/5979
- Specify that new trunks are now PJSIP https://github.com/nethesis/dev/issues/6002
- add note for app notifications backup restore https://github.com/nethesis/dev/issues/6021
- Add outbound dialtone to NethHotel

Update NethVoice 14 docs 

---

admin-manual/app_mobile.rst

added requirement of static public ip and rtp port range

Add info for mobile app

---

admin-manual/nethifier.rst

Added Windows 11 compatibility and path to customize html popup

Added info on nethifier customization

---

admin-manual/app_mobile.rst

Add required version OS for Mobile App and remove Wave

Add required version OS for Mobile App and remove Wave

---

admin-manual/release_notes.rst

Add new updates

---

admin-manual/nethifier.rst

Added brief explanation on USB Telephony headset function keys usage

Headset function keys reference

---

admin-manual/wizard.rst
admin-manual/wizard2.rst

Change wizard order for new profile settings (route)

Change wizard order

---

admin-manual/release_notes.rst

Add new presence and USB headphone support.

Update release notes

---

admin-manual/nethifier.rst

Logitech  H650e USB
Snom A330M A330D USB 
Sennheiser SC 30 USB

Add headphone in Nethifier support list

---

admin-manual/provisioning_gateway.rst
admin-manual/provisioning_phone2.rst

https://github.com/nethesis/dev/issues/6199
https://github.com/nethesis/dev/issues/6196

Add Grandstream FXS and NethPhone X210

---

admin-manual/provisioning_gateway.rst

https://github.com/nethesis/dev/issues/6196

Add note for Grandstream eth

---

admin-manual/howto.rst
admin-manual/wizard2_others.rst

https://github.com/nethesis/dev/issues/6173

Add sample custom scripts documentation

---

admin-manual/howto.rst
admin-manual/nethifier.rst
admin-manual/provisioning_gateway.rst
admin-manual/provisioning_phone2.rst
admin-manual/release_notes.rst
admin-manual/wizard2_others.rst

Add sample custom scripts documentation
* Add documentation for custom lookup scripts
* Add documentation for sample script that sends call detail using an API
* Add documentation for parametrized url customercode

Update NV14 docs

---

admin-manual/hotel.rst
admin-manual/installazione.rst
admin-manual/introduzione.rst
admin-manual/wizard.rst
admin-manual/wizard2.rst
admin-manual/wizard2_others.rst

Fix menu and add profile permissions

Fix menu and add profile permissions

---

admin-manual/provisioning_phone2.rst
admin-manual/release_notes.rst

https://github.com/nethesis/dev/issues/6207

Add Fanvil V series to provisioning

---

admin-manual/index.rst
admin-manual/integration.rst

https://github.com/nethesis/dev/issues/6209

Add integration section for vte

---

admin-manual/provisioning_phone2.rst

https://github.com/nethesis/dev/issues/6215

Add new Snom models D140 D150 D862 D865

---

admin-manual/provisioning_phone2.rst

https://github.com/nethesis/dev/issues/6214

Update Fanvil models list

---

admin-manual/provisioning_phone2.rst

https://github.com/nethesis/dev/issues/6217

Add Yealink T31W, T34W and Fanvil V63
